base_conhecimento = [
    "Após picada de mosquito, lave o local com água e sabão e evite coçar para prevenir infecção.",
    "Durante uma crise de asma, use o broncodilatador prescrito, sente-se em posição confortável e mantenha a calma. Procure atendimento médico se não houver melhora rápida.",
    "Em caso de Alzheimer, siga as orientações médicas para controle dos sintomas e suporte ao paciente e familiares.",
    "Em caso de COVID-19, siga as orientações das autoridades de saúde, isole-se e procure atendimento médico se necessário.",
    "Em caso de TEA (Transtorno do Espectro Autista), procure atendimento multidisciplinar com neurologista, fonoaudiólogo e terapeuta ocupacional.",
    "Em caso de acne, siga as orientações do dermatologista para tratamento com produtos tópicos e/ou orais.",
    "Em caso de aneurisma cerebral, procure atendimento médico para avaliação e possível tratamento.",
    "Em caso de asma, siga o plano de tratamento médico e tenha sempre a bombinha de resgate por perto.",
    "Em caso de bronquite, procure um médico para tratamento adequado.",
    "Em caso de bursite, repouse a área afetada e procure orientação médica.",
    "Em caso de carbúnculo, procure um médico para tratamento, que pode incluir antibióticos e drenagem.",
    "Em caso de chikungunya, siga as orientações médicas para controle da dor e outros sintomas.",
    "Em caso de cifose, siga as orientações médicas, que podem incluir fisioterapia e exercícios posturais.",
    "Em caso de coqueluche, procure atendimento médico para tratamento com antibióticos.",
    "Em caso de crise de ansiedade, tente manter a calma e respirar fundo.",
    "Em caso de câncer de pulmão, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de cólica menstrual intensa, repouse e use analgésicos se necessário.",
    "Em caso de degeneração macular, siga as orientações do oftalmologista para controle da progressão da doença.",
    "Em caso de dermatite de contato, evite o contato com a substância irritante e use cremes com corticoides se necessário.",
    "Em caso de dermatite seborreica, use shampoos antifúngicos e consulte um dermatologista para controle da oleosidade e inflamação.",
    "Em caso de desmaio, deite a pessoa de costas e eleve as pernas para melhorar o fluxo sanguíneo ao cérebro.",
    "Em caso de diarreia persistente, mantenha-se hidratado e procure um médico se houver outros sintomas como febre ou sangue nas fezes.",
    "Em caso de dor abdominal intensa, evite comer ou beber até ser avaliado por um médico. Procure atendimento médico imediatamente.",
    "Em caso de dor abdominal intensa, procure atendimento médico imediatamente.",
    "Em caso de dor de barriga leve, repouse e mantenha-se hidratado",
    "Em caso de dor de barriga súbita e muito forte, procure atendimento médico de emergência",
    "Em caso de dor de dente, enxágue a boca com água morna, use fio dental para remover resíduos e evite aplicar calor diretamente na área. Procure um dentista o quanto antes.",
    "Em caso de dor de ouvido, aplique compressas mornas e procure um médico se a dor persistir ou houver secreção.",
    "Em caso de dor nas articulações, evite esforço físico e aplique gelo na área afetada. Se a dor persistir ou houver inchaço, procure avaliação médica.",
    "Em caso de dor nas costas, aplique compressas mornas e evite esforço físico. Se a dor persistir ou for intensa, procure avaliação médica.",
    "Em caso de dor nas costas, aplique compressas mornas, evite esforço físico e mantenha uma boa postura. Se a dor persistir ou for intensa, procure avaliação médica.",
    "Em caso de dor nas pernas, evite esforço físico, aplique compressas frias ou mornas conforme o alívio percebido e mantenha as pernas elevadas. Se a dor for intensa, persistente ou acompanhada de inchaço, procure avaliação médica.",
    "Em caso de dor no joelho, evite esforço, aplique gelo por 20 minutos e mantenha a perna elevada. Se a dor persistir, estiver associada a inchaço ou dificuldade para se mover, procure avaliação médica.",
    "Em caso de dor no peito repentina e intensa, procure atendimento médico de emergência.",
    "Em caso de dor no peito, procure atendimento médico imediatamente, especialmente se acompanhada de falta de ar, sudorese ou dor irradiada para o braço esquerdo.",
    "Em caso de entorse, aplique gelo por 20 minutos, eleve o membro afetado e evite apoiar peso. Procure avaliação médica para descartar fraturas.",
    "Em caso de epilepsia, siga rigorosamente o tratamento com medicamentos anticonvulsivantes prescrito pelo médico.",
    "Em caso de erisipela, procure um médico para tratamento com antibióticos.",
    "Em caso de esclerose lateral amiotrófica (ELA), siga as orientações médicas para suporte e cuidados.",
    "Em caso de esquizofrenia, é essencial acompanhamento psiquiátrico contínuo e adesão ao tratamento medicamentoso e psicossocial.",
    "Em caso de febre alta, mantenha-se hidratado, use roupas leves e, se necessário, use medicamentos antitérmicos conforme orientação médica. Procure atendimento se a febre persistir por mais de 48 horas ou vier acompanhada de outros sintomas graves.",
    "Em caso de febre alta, procure um médico para identificar a causa.",
    "Em caso de fibromialgia, siga as orientações médicas para controle da dor e outros sintomas.",
    "Em caso de fibrose cística, siga rigorosamente o tratamento multidisciplinar.",
    "Em caso de gastrite, siga a dieta recomendada pelo médico e use medicamentos se prescritos.",
    "Em caso de gonorreia, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Em caso de gota, siga as orientações médicas para controle da dor e prevenção de crises.",
    "Em caso de hepatite B, siga o acompanhamento médico e o tratamento indicado.",
    "Em caso de hiperglicemia (alto nível de açúcar no sangue) em diabéticos, siga as orientações médicas.",
    "Em caso de hipertensão, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Em caso de hipertireoidismo, siga o tratamento médico indicado.",
    "Em caso de hipotermia, leve a pessoa para um local aquecido e cubra-a com cobertores.",
    "Em caso de infarto agudo do miocárdio, procure atendimento médico de emergência.",
    "Em caso de insuficiência cardíaca, siga rigorosamente o tratamento médico, incluindo medicamentos e dieta.",
    "Em caso de insônia, tente criar uma rotina de sono regular e um ambiente propício para o descanso.",
    "Em caso de intoxicação, ligue para o centro de controle de intoxicações e siga as orientações.",
    "Em caso de linfoma, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de lupus eritematoso sistêmico, siga rigorosamente o tratamento médico com imunossupressores e outros medicamentos.",
    "Em caso de mordida de animal peçonhento, como cobra, mantenha a vítima calma, imobilize o local e busque atendimento médico imediatamente.",
    "Em caso de mordida de animal, lave bem o ferimento com água e sabão e procure atendimento médico.",
    "Em caso de neuropatia periférica, procure um médico para identificar a causa e seguir o tratamento adequado.",
    "Em caso de osteoporose, siga as orientações médicas para prevenção de fraturas, incluindo suplementação de cálcio e vitamina D e medicamentos se necessário.",
    "Em caso de otite (dor de ouvido), procure um otorrinolaringologista.",
    "Em caso de otite média, procure um médico para tratamento adequado.",
    "Em caso de overdose, procure atendimento médico de emergência.",
    "Em caso de parada cardíaca, inicie a massagem cardíaca com compressões firmes e ritmadas no centro do peito.",
    "Em caso de pedra nos rins, procure atendimento médico para controle da dor e tratamento.",
    "Em caso de picada de abelha, remova o ferrão com cuidado, lave a área com água e sabão e aplique uma compressa fria.",
    "Em caso de picada de carrapato, remova o inseto cuidadosamente, lave a área com água e sabão e observe sinais de infecção.",
    "Em caso de picada de cobra, mantenha a pessoa calma e imóvel, lave o local com água e sabão e procure atendimento médico de emergência levando a cobra (se seguro) ou fotos dela para identificação do veneno.",
    "Em caso de picada de cobra, mantenha a vítima calma, imobilize o membro afetado e procure atendimento médico urgente.",
    "Em caso de picada de escorpião, lave o local com água e sabão e procure atendimento médico imediatamente.",
    "Em caso de picada de formiga venenosa, lave a área com água e sabão e procure atendimento médico se houver reação intensa.",
    "Em caso de picada de marimbondo, lave o local com água e sabão e aplique compressa fria para reduzir a dor e o inchaço.",
    "Em caso de poliomielite, procure atendimento médico imediatamente.",
    "Em caso de queda, avalie a pessoa e procure atendimento médico se houver dor intensa ou incapacidade de movimentar a área afetada.",
    "Em caso de queimadura, lave a área com água corrente fria por pelo menos 10 minutos e cubra com um pano limpo.",
    "Em caso de rompimento de ligamento, procure atendimento médico para avaliação e tratamento.",
    "Em caso de sangramento nasal, incline a cabeça para frente e pressione a narina que está sangrando por alguns minutos.",
    "Em caso de sarampo, isole-se e procure atendimento médico.",
    "Em caso de síndrome do intestino irritável, siga a dieta e as orientações médicas para controle dos sintomas.",
    "Em caso de síndrome do túnel do carpo, siga as orientações médicas, que podem incluir repouso, uso de órtese e, em alguns casos, cirurgia.",
    "Em caso de tendinite, repouse a área afetada e aplique gelo.",
    "Em caso de torcicolo, aplique calor e faça movimentos suaves.",
    "Em caso de traumatismo cranioencefálico, procure atendimento médico de emergência.",
    "Em casos de diarreia intensa, reponha líquidos com soluções de reidratação oral",
    "Evite alimentos gordurosos ou muito condimentados em caso de dor de barriga",
    "Evite automedicação em casos de dor abdominal intensa ou persistente",
    "Mantenha uma alimentação leve, com líquidos e alimentos de fácil digestão, durante episódios de dor de barriga",
    "Para DPOC (Doença Pulmonar Obstrutiva Crônica), evite exposição a fumaça, siga o tratamento com broncodilatadores e faça fisioterapia respiratória.",
    "Para acidente isquêmico transitório (AIT), procure atendimento médico para avaliação e prevenção de AVC.",
    "Para afogamento, inicie a ressuscitação cardiopulmonar (RCP) imediatamente e procure atendimento médico.",
    "Para alívio de hemorroidas, mantenha a região limpa, faça banhos de assento com água morna e evite esforço ao evacuar. Consulte um médico se houver sangramento, dor intensa ou persistência dos sintomas.",
    "Para anemia falciforme, siga o tratamento com acompanhamento hematológico regular e evite situações que desencadeiem crises.",
    "Para arritmia cardíaca, siga as orientações do cardiologista para controle do ritmo cardíaco.",
    "Para asma, siga o plano de tratamento médico e tenha sempre a bombinha de resgate por perto.",
    "Para azia ou indigestão, evite alimentos pesados e procure um médico se os sintomas persistirem.",
    "Para candidíase, use antifúngicos tópicos ou orais conforme orientação médica.",
    "Para catarata, consulte um oftalmologista para avaliação e possível cirurgia.",
    "Para caxumba, isole-se e procure atendimento médico para controle dos sintomas.",
    "Para celulite (infecção de pele), procure um médico para tratamento com antibióticos.",
    "Para colite ulcerativa, siga o tratamento médico para controle da inflamação.",
    "Para conjuntivite, lave os olhos com soro fisiológico e procure um oftalmologista.",
    "Para constipação, aumente a ingestão de fibras e água e procure um médico se o problema persistir.",
    "Para cortes profundos, lave com água corrente, aplique pressão com um pano limpo para estancar o sangramento e procure atendimento médico para avaliação e possível sutura.",
    "Para cortes profundos, pressione com um pano limpo para estancar o sangue e procure atendimento médico.",
    "Para câncer de pele, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Para câncer de próstata, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Para diabetes, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Para difteria, procure atendimento médico urgente para tratamento com antitoxina e antibióticos.",
    "Para distensão muscular, repouse a área afetada e aplique gelo.",
    "Para doença celíaca, siga uma dieta totalmente isenta de glúten e procure acompanhamento com nutricionista e gastroenterologista.",
    "Para dor abdominal intensa, evite comer ou beber até ser avaliado por um médico. Procure atendimento médico imediatamente.",
    "Para dor ciática, procure um médico ou fisioterapeuta.",
    "Para dor de barriga causada por gases, caminhe levemente e evite bebidas gaseificadas",
    "Para dor de cabeça leve, repouse em um local escuro e arejado.",
    "Para dor de estômago, evite alimentos sólidos e procure um médico se a dor persistir ou houver vômito.",
    "Para dor de garganta, faça gargarejos com água morna e sal e procure um médico se a dor persistir ou houver dificuldade para engolir.",
    "Para dor nas pernas, evite esforço físico, aplique compressas frias ou mornas conforme o alívio percebido e mantenha as pernas elevadas. Se a dor for intensa, persistente ou acompanhada de inchaço, procure avaliação médica.",
    "Para embolia pulmonar, procure atendimento médico de emergência.",
    "Para encefalite, procure atendimento médico urgente.",
    "Para endometriose, procure um ginecologista. O tratamento pode incluir medicamentos hormonais e, em alguns casos, cirurgia.",
    "Para enfisema pulmonar, siga as orientações médicas para controle dos sintomas e melhora da respiração.",
    "Para epitrocleíte, repouse o braço e procure orientação médica.",
    "Para esclerose múltipla, siga as orientações médicas para controle dos sintomas e tratamento.",
    "Para espondilite anquilosante, siga as orientações médicas para controle da dor e da rigidez.",
    "Para estenose espinhal, siga as orientações médicas para controle da dor e outros sintomas.",
    "Para faringite, procure um médico para tratamento adequado.",
    "Para fascite plantar, siga as orientações médicas, que podem incluir repouso, alongamento e uso de palmilhas.",
    "Para febre amarela, procure um médico para diagnóstico e tratamento.",
    "Para fratura exposta, cubra o ferimento com um pano limpo sem pressionar e procure atendimento médico de emergência.",
    "Para furúnculo, aplique compressas mornas e procure um médico se não melhorar ou se houver sinais de infecção mais grave.",
    "Para gota, siga as orientações médicas para controle da dor e prevenção de crises.",
    "Para hanseníase, siga rigorosamente o tratamento com poliquimioterapia prescrito pelo médico.",
    "Para hepatite A, repouse e siga as orientações médicas.",
    "Para herpes labial, use medicamentos antivirais tópicos.",
    "Para hipoglicemia (baixo nível de açúcar no sangue), ofereça algo doce para a pessoa consumir.",
    "Para hipotireoidismo, siga rigorosamente o tratamento com levotiroxina prescrito pelo médico.",
    "Para hérnia umbilical em adultos, consulte um cirurgião se houver dor, aumento de volume ou sinais de complicação.",
    "Para insolação, leve a pessoa para um local fresco e ofereça líquidos.",
    "Para insuficiência renal, siga rigorosamente o tratamento médico, incluindo dieta e possível diálise ou transplante.",
    "Para leucemia, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Para lordose, siga as orientações médicas, que podem incluir fisioterapia e exercícios de fortalecimento.",
    "Para osteoartrite, siga as orientações médicas para controle da dor e melhora da mobilidade.",
    "Para pequenos arranhões, lave com água e sabão e cubra com um curativo limpo.",
    "Para picada de aranha, lave o local com água e sabão e procure atendimento médico se houver sintomas como dor intensa ou dificuldade para respirar.",
    "Para picada de inseto, lave o local com água e sabão e aplique compressa fria para aliviar a dor e o inchaço.",
    "Para psoríase, siga as orientações do dermatologista para tratamento das lesões de pele.",
    "Para queimaduras químicas, lave a área afetada com água corrente por pelo menos 20 minutos e procure atendimento médico.",
    "Para reações adversas a medicamentos, procure atendimento médico imediatamente.",
    "Para reações alérgicas leves, como coceira e erupção cutânea, use um anti-histamínico.",
    "Para refluxo gastroesofágico, evite alimentos que desencadeiam os sintomas e use medicamentos se prescritos.",
    "Para sintomas de depressão, como tristeza persistente e perda de interesse, procure um profissional de saúde mental.",
    "Para sinusite, procure um médico para tratamento com medicamentos e/ou outras medidas.",
    "Para sífilis, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Para síndrome de Guillain-Barré, procure atendimento médico para tratamento e suporte.",
    "Para torções, imobilize a articulação e procure orientação médica.",
    "Para transtorno bipolar, siga rigorosamente o tratamento com estabilizadores de humor e acompanhamento psiquiátrico.",
    "Para tuberculose, siga rigorosamente o tratamento com antibióticos prescrito pelo médico.",
    "Para urticária, use anti-histamínicos e procure um médico se os sintomas persistirem ou forem graves.",
    "Para zika vírus, siga as orientações médicas para controle dos sintomas.",
    "Se a dor de barriga for acompanhada de febre, vômito ou sangue nas fezes, procure atendimento médico",
    "Se a dor de barriga persistir por mais de 24 horas, procure orientação médica",
    "Se alguém apresentar sinais de desidratação, como boca seca e urina escura, ofereça líquidos e procure ajuda médica se não houver melhora.",
    "Se alguém estiver engasgado e não conseguir respirar, aplique a manobra de Heimlich.",
    "Se alguém tiver um ataque de pânico, ofereça apoio e procure ajuda profissional.",
    "Se alguém tiver uma crise convulsiva, proteja a cabeça da pessoa e afaste objetos perigosos, sem tentar conter os movimentos.",
    "Se for picado por peixe venenoso, como bagre ou arraia, lave o ferimento e mergulhe o local em água quente enquanto aguarda ajuda médica.",
    "Se for picado por uma lacraia, lave a área com água e sabão e aplique compressa fria para aliviar a dor.",
    "Se houver AIDS, siga rigorosamente o tratamento antirretroviral prescrito pelo médico e mantenha acompanhamento regular.",
    "Se houver Parkinson, siga as orientações médicas para controle dos sintomas e melhora da qualidade de vida.",
    "Se houver acidente de trânsito, verifique se há feridos e chame os serviços de emergência.",
    "Se houver acidente vascular cerebral (AVC), procure atendimento médico de emergência.",
    "Se houver amigdalite, procure um médico para tratamento com antibióticos se necessário.",
    "Se houver anemia, procure um médico para identificar a causa e seguir o tratamento adequado.",
    "Se houver angina, procure atendimento médico para avaliação e tratamento.",
    "Se houver artrite reumatoide, siga rigorosamente o tratamento médico com medicamentos para controle da inflamação e da dor.",
    "Se houver bronquiolite, procure um médico, especialmente em bebês e crianças pequenas.",
    "Se houver bursite, repouse a área afetada e procure orientação médica.",
    "Se houver choque elétrico, desligue a fonte de energia antes de tocar na vítima e procure atendimento médico.",
    "Se houver clamídia, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Se houver colesterol alto, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Se houver contato com substâncias tóxicas, lave a área abundantemente com água corrente e procure ajuda médica.",
    "Se houver contusão, aplique gelo na área afetada.",
    "Se houver câncer de cólon e reto, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Se houver câncer de mama, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Se houver dengue, mantenha-se hidratado e procure atendimento médico para controle dos sintomas.",
    "Se houver dificuldade para respirar, procure ajuda médica imediatamente.",
    "Se houver doença de Crohn, siga o tratamento médico para controle da inflamação.",
    "Se houver dor ao urinar, beba bastante água e procure um médico para avaliação.",
    "Se houver dor de cabeça intensa, desmaio ou confusão mental, procure atendimento médico imediatamente.",
    "Se houver dor de garganta intensa, procure um médico para descartar infecções.",
    "Se houver dor lombar persistente, procure um médico ou fisioterapeuta.",
    "Se houver dor no joelho, evite esforço, aplique gelo por 20 minutos e mantenha a perna elevada. Se a dor persistir, estiver associada a inchaço ou dificuldade para se mover, procure avaliação médica.",
    "Se houver dor no peito, procure atendimento médico imediatamente.",
    "Se houver eczema (dermatite atópica), siga as orientações do dermatologista para controle da inflamação e coceira.",
    "Se houver epicondilite, repouse o braço e procure orientação médica.",
    "Se houver escoliose, siga as orientações médicas, que podem incluir fisioterapia ou uso de colete.",
    "Se houver fratura suspeita, imobilize a área e evite movimentar a pessoa até a chegada de ajuda especializada.",
    "Se houver glaucoma, siga rigorosamente o tratamento oftalmológico para evitar a perda da visão.",
    "Se houver hemorragia, aplique pressão direta sobre o local e procure atendimento médico.",
    "Se houver hepatite C, siga o acompanhamento médico e o tratamento indicado.",
    "Se houver herpes zoster, procure um médico para tratamento com antivirais e controle da dor.",
    "Se houver hérnia de disco, siga as orientações médicas, que podem incluir repouso, fisioterapia e, em alguns casos, cirurgia.",
    "Se houver hérnia inguinal, evite levantar peso e procure um cirurgião para avaliação de necessidade de correção cirúrgica.",
    "Se houver impetigo, procure um médico para tratamento com antibióticos tópicos ou orais.",
    "Se houver infecção renal, procure atendimento médico para tratamento com antibióticos.",
    "Se houver ingestão de substâncias tóxicas, não induza o vômito a menos que indicado por um profissional de saúde.",
    "Se houver intolerância à lactose, evite produtos com lactose e consulte um nutricionista para orientação sobre substituições.",
    "Se houver luxação, procure atendimento médico para que a articulação seja recolocada no lugar.",
    "Se houver malária, procure atendimento médico imediato para tratamento específico.",
    "Se houver meningite, procure atendimento médico urgente.",
    "Se houver miastenia gravis, siga o tratamento médico para controle da fraqueza muscular.",
    "Se houver micose de pele, use antifúngicos tópicos conforme orientação médica.",
    "Se houver picada de aranha, lave o local com água e sabão, mantenha a área elevada e procure atendimento médico.",
    "Se houver picada de taturana, lave a área com água fria corrente sem esfregar e procure atendimento médico.",
    "Se houver pneumonia, siga o tratamento médico com antibióticos e repouso.",
    "Se houver queimadura solar, aplique hidratante e evite a exposição ao sol.",
    "Se houver rinite alérgica, evite o contato com alérgenos e use medicamentos anti-histamínicos ou corticoides nasais conforme orientação médica.",
    "Se houver rosácea, siga as orientações do dermatologista para controle dos sintomas.",
    "Se houver rubéola, procure atendimento médico e evite contato com grávidas.",
    "Se houver sinais de TDAH, como desatenção e impulsividade, procure um neurologista ou psiquiatra para diagnóstico e tratamento.",
    "Se houver sinais de acidente vascular cerebral (AVC), como dificuldade para falar ou paralisia em um lado do corpo, chame o serviço de emergência.",
    "Se houver sinais de alergia respiratória, como espirros e coriza, evite o contato com alérgenos e use anti-histamínicos se necessário.",
    "Se houver sinais de desidratação junto com dor de barriga, como boca seca e tontura, procure ajuda médica imediatamente",
    "Se houver sinais de desidratação, como boca seca e urina escura, ofereça líquidos e procure ajuda médica se não houver melhora.",
    "Se houver sinais de infecção urinária, como dor ao urinar e aumento da frequência urinária, procure um médico.",
    "Se houver suspeita de insolação, leve a pessoa para um local fresco e ofereça líquidos.",
    "Se houver síndrome de Sjögren, siga as orientações médicas para controle dos sintomas de secura.",
    "Se houver tendinite, repouse a área afetada e aplique gelo.",
    "Se houver trombose venosa profunda, procure atendimento médico imediato para tratamento com anticoagulantes.",
    "Se houver tétano, procure atendimento médico urgente para tratamento com imunoglobulina e vacina.",
    "Se houver varizes com dor ou inchaço, eleve as pernas, evite ficar parado muito tempo e procure um angiologista para avaliação.",
    "Se houver vômito persistente, mantenha-se hidratado e procure um médico se não houver melhora.",
    "Se houver úlcera péptica, siga o tratamento médico com medicamentos e dieta.",
    "Se ocorrer entorse, aplique gelo na área afetada e mantenha-a elevada.",
    "Se picado por uma vespa, lave o local com água e sabão e aplique gelo para reduzir o inchaço.",
    "Em caso de esofagite, evite alimentos ácidos ou apimentados e siga o tratamento médico indicado.",
    "Em caso de pancreatite aguda, evite ingestão de alimentos e procure atendimento médico de emergência.",
    "Para doença de Ménière, evite sal em excesso e siga o tratamento médico para controlar vertigens e perda auditiva.",
    "Para endocardite infecciosa, siga rigorosamente o tratamento com antibióticos e monitore complicações cardíacas.",
    "Para síndrome metabólica, mantenha alimentação saudável, pratique exercícios e siga o tratamento médico.",
    "Para artrite psoriásica, siga o tratamento indicado por reumatologista, incluindo medicamentos e fisioterapia.",
    "Para síndrome das pernas inquietas, mantenha rotina de sono regular e consulte um neurologista.",
    "Para esofagite eosinofílica, siga dieta orientada por gastroenterologista e evite alérgenos alimentares.",
    "Para doença arterial periférica, evite tabagismo, pratique atividade física e siga o tratamento médico.",
    "Para hepatite autoimune, siga tratamento com imunossupressores e acompanhamento com hepatologista.",
    "Para doença de Behçet, procure um reumatologista para controle das inflamações e lesões recorrentes.",
    "Para síndrome nefrótica, siga o tratamento com medicamentos e dieta com restrição de sal e proteínas.",
    "Para púrpura trombocitopênica idiopática (PTI), procure um hematologista para tratamento e acompanhamento.",
    "Para displasia broncopulmonar em bebês prematuros, siga o acompanhamento com pediatra e pneumologista infantil.",
    "Para esofagite de refluxo, eleve a cabeceira da cama e evite refeições pesadas à noite.",
    "Para colangite esclerosante primária, mantenha acompanhamento com hepatologista e controle dos sintomas.",
    "Para hiperplasia adrenal congênita, siga o tratamento hormonal indicado e monitore regularmente os níveis hormonais.",
    "Para distúrbios de ansiedade generalizada, procure um psicólogo ou psiquiatra para avaliação e tratamento.",
    "Para transtorno obsessivo-compulsivo (TOC), siga o tratamento com terapia cognitivo-comportamental e/ou medicamentos.",
    "Para síndrome do pânico, busque tratamento com psicoterapia e acompanhamento psiquiátrico."

    "Procure um cardiologista: Hipertensão, Infarto, Arritmia, Insuficiência cardíaca",
    "Procure um dermatologista: Acne, Eczema, Psoríase, Câncer de pele",
    "Procure um endocrinologista: Diabetes, Hipotireoidismo, Hipertireoidismo, Obesidade",
    "Procure um fisioterapeuta: Reabilitação, Exercícios terapêuticos, Tratamento de dor, Prevenção de lesões",
    "Procure um gastroenterologista: Doenças do fígado, Doenças intestinais, Refluxo gastroesofágico, Úlceras",
    "Procure um geriatra: Doenças crônicas, Cuidados paliativos, Saúde mental, Mobilidade",
    "Procure um ginecologista: Menstruação, Gravidez, Menopausa, Infecções vaginais",
    "Procure um hematologista: Anemia, Leucemia, Linfoma, Hemofilia",
    "Procure um infectologista: Infecções, Doenças infecciosas, Imunizações, Tratamento de doenças infecciosas",
    "Procure um neurologista: Dores de cabeça, Epilepsia, Doença de Parkinson, Esclerose múltipla",
    "Procure um nutricionista: Dieta equilibrada, Controle de peso, Doenças metabólicas, Alergias alimentares",
    "Procure um oftalmologista: Problemas de visão, Catarata, Glaucoma, Doenças da retina",
    "Procure um oncologista: Câncer, Quimioterapia, Radioterapia, Cuidados paliativos",
    "Procure um ortopedista: Fraturas, Entorses, Lesões esportivas, Problemas articulares",
    "Procure um otorrinolaringologista: Problemas auditivos, Sinusite, Amigdalite, Zumbido",
    "Procure um pediatra: Infecções, Doenças respiratórias, Alergias, Doenças crônicas",
    "Procure um pneumologista: Asma, DPOC, Pneumonia, Apneia do sono",
    "Procure um psicólogo: Depressão, Ansiedade, Estresse, Relacionamentos",
    "Procure um psiquiatra: Depressão, Ansiedade, Transtornos alimentares, Esquizofrenia",
    "Procure um reumatologista: Artrite, Lupus, Fibromialgia, Osteoporose",
    "Procure um urologista: Infecções urinárias, Cálculos renais, Problemas de próstata, Disfunção erétil"
]