base_conhecimento = [
    "Em caso de queimadura, lave a área com água corrente fria por pelo menos 10 minutos e cubra com um pano limpo.",
    "Se alguém estiver engasgado e não conseguir respirar, aplique a manobra de Heimlich.",
    "Em caso de desmaio, deite a pessoa de costas e eleve as pernas para melhorar o fluxo sanguíneo ao cérebro.",
    "Para cortes profundos, pressione com um pano limpo para estancar o sangue e procure atendimento médico.",
    "Se houver fratura suspeita, imobilize a área e evite movimentar a pessoa até a chegada de ajuda especializada.",
    "Em caso de parada cardíaca, inicie a massagem cardíaca com compressões firmes e ritmadas no centro do peito.",
    "Se alguém tiver uma crise convulsiva, proteja a cabeça da pessoa e afaste objetos perigosos, sem tentar conter os movimentos.",
    "Para picada de inseto, lave o local com água e sabão e aplique compressa fria para aliviar a dor e o inchaço.",
    "Em caso de sangramento nasal, incline a cabeça para frente e pressione a narina que está sangrando por alguns minutos.",
    "Se ocorrer entorse, aplique gelo na área afetada e mantenha-a elevada.",
    "Para dor de cabeça leve, repouse em um local escuro e arejado.",
    "Em caso de febre alta, procure um médico para identificar a causa.",
    "Se houver suspeita de insolação, leve a pessoa para um local fresco e ofereça líquidos.",
    "Para torções, imobilize a articulação e procure orientação médica.",
    "Em caso de mordida de animal, lave bem o ferimento com água e sabão e procure atendimento médico.",
    "Se houver contato com substâncias tóxicas, lave a área abundantemente com água corrente e procure ajuda médica.",
    "Para pequenos arranhões, lave com água e sabão e cubra com um curativo limpo.",
    "Em caso de dor abdominal intensa, procure atendimento médico imediatamente.",
    "Se houver sinais de acidente vascular cerebral (AVC), como dificuldade para falar ou paralisia em um lado do corpo, chame o serviço de emergência.",
    "Para reações alérgicas leves, como coceira e erupção cutânea, use um anti-histamínico.",
    "Em caso de dor no peito repentina e intensa, procure atendimento médico de emergência.",
    "Se houver dificuldade para respirar, procure ajuda médica imediatamente.",
    "Para hipoglicemia (baixo nível de açúcar no sangue), ofereça algo doce para a pessoa consumir.",
    "Em caso de hiperglicemia (alto nível de açúcar no sangue) em diabéticos, siga as orientações médicas.",
    "Se alguém apresentar sinais de desidratação, como boca seca e urina escura, ofereça líquidos e procure ajuda médica se não houver melhora.",
    "Para conjuntivite, lave os olhos com soro fisiológico e procure um oftalmologista.",
    "Em caso de otite (dor de ouvido), procure um otorrinolaringologista.",
    "Se houver dor de garganta intensa, procure um médico para descartar infecções.",
    "Para azia ou indigestão, evite alimentos pesados e procure um médico se os sintomas persistirem.",
    "Em caso de diarreia persistente, mantenha-se hidratado e procure um médico se houver outros sintomas como febre ou sangue nas fezes.",
    "Se houver vômito persistente, mantenha-se hidratado e procure um médico se não houver melhora.",
    "Para constipação, aumente a ingestão de fibras e água e procure um médico se o problema persistir.",
    "Em caso de crise de ansiedade, tente manter a calma e respirar fundo.",
    "Se alguém tiver um ataque de pânico, ofereça apoio e procure ajuda profissional.",
    "Para sintomas de depressão, como tristeza persistente e perda de interesse, procure um profissional de saúde mental.",
    "Em caso de insônia, tente criar uma rotina de sono regular e um ambiente propício para o descanso.",
    "Se houver sinais de infecção urinária, como dor ao urinar e aumento da frequência urinária, procure um médico.",
    "Para herpes labial, use medicamentos antivirais tópicos.",
    "Em caso de cólica menstrual intensa, repouse e use analgésicos se necessário.",
    "Se houver dor lombar persistente, procure um médico ou fisioterapeuta.",
    "Para dor ciática, procure um médico ou fisioterapeuta.",
    "Em caso de tendinite, repouse a área afetada e aplique gelo.",
    "Se houver bursite, repouse a área afetada e procure orientação médica.",
    "Para osteoartrite, siga as orientações médicas para controle da dor e melhora da mobilidade.",
    "Em caso de gota, siga as orientações médicas para controle da dor e prevenção de crises.",
    "Se houver sinais de alergia respiratória, como espirros e coriza, evite o contato com alérgenos e use anti-histamínicos se necessário.",
    "Para asma, siga o plano de tratamento médico e tenha sempre a bombinha de resgate por perto.",
    "Em caso de bronquite, procure um médico para tratamento adequado.",
    "Se houver pneumonia, siga o tratamento médico com antibióticos e repouso.",
    "Para tuberculose, siga rigorosamente o tratamento com antibióticos prescrito pelo médico.",
    "Em caso de COVID-19, siga as orientações das autoridades de saúde, isole-se e procure atendimento médico se necessário.",
    "Se houver dengue, mantenha-se hidratado e procure atendimento médico para controle dos sintomas.",
    "Para zika vírus, siga as orientações médicas para controle dos sintomas.",
    "Em caso de chikungunya, siga as orientações médicas para controle da dor e outros sintomas.",
    "Se houver malária, procure atendimento médico imediato para tratamento específico.",
    "Para febre amarela, procure um médico para diagnóstico e tratamento.",
    "Em caso de sarampo, isole-se e procure atendimento médico.",
    "Se houver rubéola, procure atendimento médico e evite contato com grávidas.",
    "Para caxumba, isole-se e procure atendimento médico para controle dos sintomas.",
    "Em caso de poliomielite, procure atendimento médico imediatamente.",
    "Se houver tétano, procure atendimento médico urgente para tratamento com imunoglobulina e vacina.",
    "Para difteria, procure atendimento médico urgente para tratamento com antitoxina e antibióticos.",
    "Em caso de coqueluche, procure atendimento médico para tratamento com antibióticos.",
    "Se houver meningite, procure atendimento médico urgente.",
    "Para hanseníase, siga rigorosamente o tratamento com poliquimioterapia prescrito pelo médico.",
    "Se houver AIDS, siga rigorosamente o tratamento antirretroviral prescrito pelo médico e mantenha acompanhamento regular.",
    "Para sífilis, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Em caso de gonorreia, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Se houver clamídia, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Para hepatite A, repouse e siga as orientações médicas.",
    "Em caso de hepatite B, siga o acompanhamento médico e o tratamento indicado.",
    "Se houver hepatite C, siga o acompanhamento médico e o tratamento indicado.",
    "Para diabetes, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Em caso de hipertensão, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Se houver colesterol alto, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Para hipotireoidismo, siga rigorosamente o tratamento com levotiroxina prescrito pelo médico.",
    "Em caso de hipertireoidismo, siga o tratamento médico indicado.",
    "Se houver anemia, procure um médico para identificar a causa e seguir o tratamento adequado.",
    "Para leucemia, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de linfoma, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Se houver câncer de mama, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Para câncer de próstata, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de câncer de pulmão, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Se houver câncer de cólon e reto, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Para câncer de pele, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de Alzheimer, siga as orientações médicas para controle dos sintomas e suporte ao paciente e familiares.",
    "Se houver Parkinson, siga as orientações médicas para controle dos sintomas e melhora da qualidade de vida.",
    "Para esclerose múltipla, siga as orientações médicas para controle dos sintomas e tratamento.",
    "Em caso de epilepsia, siga rigorosamente o tratamento com medicamentos anticonvulsivantes prescrito pelo médico.",
    "Se houver glaucoma, siga rigorosamente o tratamento oftalmológico para evitar a perda da visão.",
    "Para catarata, consulte um oftalmologista para avaliação e possível cirurgia.",
    "Em caso de degeneração macular, siga as orientações do oftalmologista para controle da progressão da doença.",
    "Se houver rinite alérgica, evite o contato com alérgenos e use medicamentos anti-histamínicos ou corticoides nasais conforme orientação médica.",
    "Para sinusite, procure um médico para tratamento com medicamentos e/ou outras medidas.",
    "Em caso de otite média, procure um médico para tratamento adequado.",
    "Se houver amigdalite, procure um médico para tratamento com antibióticos se necessário.",
    "Para faringite, procure um médico para tratamento adequado.",
    "Em caso de gastrite, siga a dieta recomendada pelo médico e use medicamentos se prescritos.",
    "Se houver úlcera péptica, siga o tratamento médico com medicamentos e dieta.",
    "Para refluxo gastroesofágico, evite alimentos que desencadeiam os sintomas e use medicamentos se prescritos.",
    "Em caso de síndrome do intestino irritável, siga a dieta e as orientações médicas para controle dos sintomas.",
    "Se houver doença de Crohn, siga o tratamento médico para controle da inflamação.",
    "Para colite ulcerativa, siga o tratamento médico para controle da inflamação.",
    "Em caso de pedra nos rins, procure atendimento médico para controle da dor e tratamento.",
    "Se houver infecção renal, procure atendimento médico para tratamento com antibióticos.",
    "Para insuficiência renal, siga rigorosamente o tratamento médico, incluindo dieta e possível diálise ou transplante.",
    "Em caso de asma, siga o plano de tratamento médico e tenha sempre a bombinha de resgate por perto.",
    "Se houver bronquiolite, procure um médico, especialmente em bebês e crianças pequenas.",
    "Para enfisema pulmonar, siga as orientações médicas para controle dos sintomas e melhora da respiração.",
    "Em caso de fibrose cística, siga rigorosamente o tratamento multidisciplinar.",
    "Se houver trombose venosa profunda, procure atendimento médico imediato para tratamento com anticoagulantes.",
    "Para embolia pulmonar, procure atendimento médico de emergência.",
    "Em caso de infarto agudo do miocárdio, procure atendimento médico de emergência.",
    "Se houver angina, procure atendimento médico para avaliação e tratamento.",
    "Para arritmia cardíaca, siga as orientações do cardiologista para controle do ritmo cardíaco.",
    "Em caso de insuficiência cardíaca, siga rigorosamente o tratamento médico, incluindo medicamentos e dieta.",
    "Se houver acidente vascular cerebral (AVC), procure atendimento médico de emergência.",
    "Para acidente isquêmico transitório (AIT), procure atendimento médico para avaliação e prevenção de AVC.",
    "Em caso de aneurisma cerebral, procure atendimento médico para avaliação e possível tratamento.",
    "Se houver meningite, procure atendimento médico urgente.",
    "Para encefalite, procure atendimento médico urgente.",
    "Em caso de esclerose lateral amiotrófica (ELA), siga as orientações médicas para suporte e cuidados.",
    "Se houver miastenia gravis, siga o tratamento médico para controle da fraqueza muscular.",
    "Para síndrome de Guillain-Barré, procure atendimento médico para tratamento e suporte.",
    "Em caso de neuropatia periférica, procure um médico para identificar a causa e seguir o tratamento adequado.",
    "Se houver herpes zoster, procure um médico para tratamento com antivirais e controle da dor.",
    "Para celulite (infecção de pele), procure um médico para tratamento com antibióticos.",
    "Em caso de erisipela, procure um médico para tratamento com antibióticos.",
    "Se houver impetigo, procure um médico para tratamento com antibióticos tópicos ou orais.",
    "Para furúnculo, aplique compressas mornas e procure um médico se não melhorar ou se houver sinais de infecção mais grave.",
    "Em caso de carbúnculo, procure um médico para tratamento, que pode incluir antibióticos e drenagem.",
    "Se houver micose de pele, use antifúngicos tópicos conforme orientação médica.",
    "Para candidíase, use antifúngicos tópicos ou orais conforme orientação médica.",
    "Em caso de dermatite de contato, evite o contato com a substância irritante e use cremes com corticoides se necessário.",
    "Se houver eczema (dermatite atópica), siga as orientações do dermatologista para controle da inflamação e coceira.",
    "Para psoríase, siga as orientações do dermatologista para tratamento das lesões de pele.",
    "Em caso de acne, siga as orientações do dermatologista para tratamento com produtos tópicos e/ou orais.",
    "Se houver rosácea, siga as orientações do dermatologista para controle dos sintomas.",
    "Para urticária, use anti-histamínicos e procure um médico se os sintomas persistirem ou forem graves.",
    "Em caso de lupus eritematoso sistêmico, siga rigorosamente o tratamento médico com imunossupressores e outros medicamentos.",
    "Se houver artrite reumatoide, siga rigorosamente o tratamento médico com medicamentos para controle da inflamação e da dor.",
    "Para espondilite anquilosante, siga as orientações médicas para controle da dor e da rigidez.",
    "Em caso de fibromialgia, siga as orientações médicas para controle da dor e outros sintomas.",
    "Se houver síndrome de Sjögren, siga as orientações médicas para controle dos sintomas de secura.",
    "Para gota, siga as orientações médicas para controle da dor e prevenção de crises.",
    "Em caso de osteoporose, siga as orientações médicas para prevenção de fraturas, incluindo suplementação de cálcio e vitamina D e medicamentos se necessário.",
    "Se houver escoliose, siga as orientações médicas, que podem incluir fisioterapia ou uso de colete.",
    "Para lordose, siga as orientações médicas, que podem incluir fisioterapia e exercícios de fortalecimento.",
    "Em caso de cifose, siga as orientações médicas, que podem incluir fisioterapia e exercícios posturais.",
    "Se houver hérnia de disco, siga as orientações médicas, que podem incluir repouso, fisioterapia e, em alguns casos, cirurgia.",
    "Para estenose espinhal, siga as orientações médicas para controle da dor e outros sintomas.",
    "Em caso de bursite, repouse a área afetada e procure orientação médica.",
    "Se houver tendinite, repouse a área afetada e aplique gelo.",
    "Para fascite plantar, siga as orientações médicas, que podem incluir repouso, alongamento e uso de palmilhas.",
    "Em caso de síndrome do túnel do carpo, siga as orientações médicas, que podem incluir repouso, uso de órtese e, em alguns casos, cirurgia.",
    "Se houver epicondilite, repouse o braço e procure orientação médica.",
    "Para epitrocleíte, repouse o braço e procure orientação médica.",
    "Em caso de torcicolo, aplique calor e faça movimentos suaves.",
    "Se houver contusão, aplique gelo na área afetada.",
    "Para distensão muscular, repouse a área afetada e aplique gelo.",
    "Em caso de rompimento de ligamento, procure atendimento médico para avaliação e tratamento.",
    "Se houver luxação, procure atendimento médico para que a articulação seja recolocada no lugar.",
    "Para fratura exposta, cubra o ferimento com um pano limpo sem pressionar e procure atendimento médico de emergência.",
    "Em caso de traumatismo cranioencefálico, procure atendimento médico de emergência.",
    "Se houver queimadura solar, aplique hidratante e evite a exposição ao sol.",
    "Para picada de aranha, lave o local com água e sabão e procure atendimento médico se houver sintomas como dor intensa ou dificuldade para respirar.",
    "Em caso de picada de cobra, mantenha a pessoa calma e imóvel, lave o local com água e sabão e procure atendimento médico de emergência levando a cobra (se seguro) ou fotos dela para identificação do veneno.",
    "Se houver choque elétrico, desligue a fonte de energia antes de tocar na vítima e procure atendimento médico.",
    "Para afogamento, inicie a ressuscitação cardiopulmonar (RCP) imediatamente e procure atendimento médico.",
    "Em caso de queda, avalie a pessoa e procure atendimento médico se houver dor intensa ou incapacidade de movimentar a área afetada.",
    "Se houver acidente de trânsito, verifique se há feridos e chame os serviços de emergência.",
    "Para queimaduras químicas, lave a área afetada com água corrente por pelo menos 20 minutos e procure atendimento médico.",
    "Em caso de intoxicação, ligue para o centro de controle de intoxicações e siga as orientações.",
    "Se houver ingestão de substâncias tóxicas, não induza o vômito a menos que indicado por um profissional de saúde.",
    "Para reações adversas a medicamentos, procure atendimento médico imediatamente.",
    "Em caso de overdose, procure atendimento médico de emergência.",
    "Se houver sinais de desidratação, como boca seca e urina escura, ofereça líquidos e procure ajuda médica se não houver melhora.",
    "Para insolação, leve a pessoa para um local fresco e ofereça líquidos.",
    "Em caso de queimadura, lave a área com água corrente fria por pelo menos 10 minutos e cubra com um pano limpo.",
    "Se alguém estiver engasgado e não conseguir respirar, aplique a manobra de Heimlich.",
    "Em caso de desmaio, deite a pessoa de costas e eleve as pernas para melhorar o fluxo sanguíneo ao cérebro.",
    "Para cortes profundos, pressione com um pano limpo para estancar o sangue e procure atendimento médico.",
    "Se houver fratura suspeita, imobilize a área e evite movimentar a pessoa até a chegada de ajuda especializada.",
    "Em caso de parada cardíaca, inicie a massagem cardíaca com compressões firmes e ritmadas no centro do peito.",
    "Se alguém tiver uma crise convulsiva, proteja a cabeça da pessoa e afaste objetos perigosos, sem tentar conter os movimentos.",
    "Para picada de inseto, lave o local com água e sabão e aplique compressa fria para aliviar a dor e o inchaço.",
    "Em caso de sangramento nasal, incline a cabeça para frente e pressione a narina que está sangrando por alguns minutos.",
    "Se ocorrer entorse, aplique gelo na área afetada e mantenha-a elevada.",
    "Para dor de cabeça leve, repouse em um local escuro e arejado.",
    "Em caso de febre alta, procure um médico para identificar a causa.",
    "Se houver suspeita de insolação, leve a pessoa para um local fresco e ofereça líquidos.",
    "Para torções, imobilize a articulação e procure orientação médica.",
    "Em caso de mordida de animal, lave bem o ferimento com água e sabão e procure atendimento médico.",
    "Se houver contato com substâncias tóxicas, lave a área abundantemente com água corrente e procure ajuda médica.",
    "Para pequenos arranhões, lave com água e sabão e cubra com um curativo limpo.",
    "Em caso de dor abdominal intensa, procure atendimento médico imediatamente.",
    "Se houver sinais de acidente vascular cerebral (AVC), como dificuldade para falar ou paralisia em um lado do corpo, chame o serviço de emergência.",
    "Para reações alérgicas leves, como coceira e erupção cutânea, use um anti-histamínico.",
    "Em caso de dor no peito repentina e intensa, procure atendimento médico de emergência.",
    "Se houver dificuldade para respirar, procure ajuda médica imediatamente.",
    "Para hipoglicemia (baixo nível de açúcar no sangue), ofereça algo doce para a pessoa consumir.",
    "Em caso de hiperglicemia (alto nível de açúcar no sangue) em diabéticos, siga as orientações médicas.",
    "Se alguém apresentar sinais de desidratação, como boca seca e urina escura, ofereça líquidos e procure ajuda médica se não houver melhora.",
    "Para conjuntivite, lave os olhos com soro fisiológico e procure um oftalmologista.",
    "Em caso de otite (dor de ouvido), procure um otorrinolaringologista.",
    "Se houver dor de garganta intensa, procure um médico para descartar infecções.",
    "Para azia ou indigestão, evite alimentos pesados e procure um médico se os sintomas persistirem.",
    "Em caso de diarreia persistente, mantenha-se hidratado e procure um médico se houver outros sintomas como febre ou sangue nas fezes.",
    "Se houver vômito persistente, mantenha-se hidratado e procure um médico se não houver melhora.",
    "Para constipação, aumente a ingestão de fibras e água e procure um médico se o problema persistir.",
    "Em caso de crise de ansiedade, tente manter a calma e respirar fundo.",
    "Se alguém tiver um ataque de pânico, ofereça apoio e procure ajuda profissional.",
    "Para sintomas de depressão, como tristeza persistente e perda de interesse, procure um profissional de saúde mental.",
    "Em caso de insônia, tente criar uma rotina de sono regular e um ambiente propício para o descanso.",
    "Se houver sinais de infecção urinária, como dor ao urinar e aumento da frequência urinária, procure um médico.",
    "Para herpes labial, use medicamentos antivirais tópicos.",
    "Em caso de cólica menstrual intensa, repouse e use analgésicos se necessário.",
    "Se houver dor lombar persistente, procure um médico ou fisioterapeuta.",
    "Para dor ciática, procure um médico ou fisioterapeuta.",
    "Em caso de tendinite, repouse a área afetada e aplique gelo.",
    "Se houver bursite, repouse a área afetada e procure orientação médica.",
    "Para osteoartrite, siga as orientações médicas para controle da dor e melhora da mobilidade.",
    "Em caso de gota, siga as orientações médicas para controle da dor e prevenção de crises.",
    "Se houver sinais de alergia respiratória, como espirros e coriza, evite o contato com alérgenos e use anti-histamínicos se necessário.",
    "Para asma, siga o plano de tratamento médico e tenha sempre a bombinha de resgate por perto.",
    "Em caso de bronquite, procure um médico para tratamento adequado.",
    "Se houver pneumonia, siga o tratamento médico com antibióticos e repouso.",
    "Para tuberculose, siga rigorosamente o tratamento com antibióticos prescrito pelo médico.",
    "Em caso de COVID-19, siga as orientações das autoridades de saúde, isole-se e procure atendimento médico se necessário.",
    "Se houver dengue, mantenha-se hidratado e procure atendimento médico para controle dos sintomas.",
    "Para zika vírus, siga as orientações médicas para controle dos sintomas.",
    "Em caso de chikungunya, siga as orientações médicas para controle da dor e outros sintomas.",
    "Se houver malária, procure atendimento médico imediato para tratamento específico.",
    "Para febre amarela, procure um médico para diagnóstico e tratamento.",
    "Em caso de sarampo, isole-se e procure atendimento médico.",
    "Se houver rubéola, procure atendimento médico e evite contato com grávidas.",
    "Para caxumba, isole-se e procure atendimento médico para controle dos sintomas.",
    "Em caso de poliomielite, procure atendimento médico imediatamente.",
    "Se houver tétano, procure atendimento médico urgente para tratamento com imunoglobulina e vacina.",
    "Para difteria, procure atendimento médico urgente para tratamento com antitoxina e antibióticos.",
    "Em caso de coqueluche, procure atendimento médico para tratamento com antibióticos.",
    "Se houver meningite, procure atendimento médico urgente.",
    "Para hanseníase, siga rigorosamente o tratamento com poliquimioterapia prescrito pelo médico.",
    "Se houver AIDS, siga rigorosamente o tratamento antirretroviral prescrito pelo médico e mantenha acompanhamento regular.",
    "Para sífilis, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Em caso de gonorreia, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Se houver clamídia, siga rigorosamente o tratamento com antibióticos prescrito pelo médico e informe seus parceiros sexuais.",
    "Para hepatite A, repouse e siga as orientações médicas.",
    "Em caso de hepatite B, siga o acompanhamento médico e o tratamento indicado.",
    "Se houver hepatite C, siga o acompanhamento médico e o tratamento indicado.",
    "Para diabetes, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Em caso de hipertensão, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Se houver colesterol alto, siga rigorosamente o plano de tratamento médico, incluindo dieta, exercícios e medicamentos.",
    "Para hipotireoidismo, siga rigorosamente o tratamento com levotiroxina prescrito pelo médico.",
    "Em caso de hipertireoidismo, siga o tratamento médico indicado.",
    "Se houver anemia, procure um médico para identificar a causa e seguir o tratamento adequado.",
    "Para leucemia, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de linfoma, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Se houver câncer de mama, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Para câncer de próstata, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de câncer de pulmão, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Se houver câncer de cólon e reto, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Para câncer de pele, siga rigorosamente o tratamento oncológico prescrito pelo médico.",
    "Em caso de Alzheimer, siga as orientações médicas para controle dos sintomas e suporte ao paciente e familiares.",
    "Se houver Parkinson, siga as orientações médicas para controle dos sintomas e melhora da qualidade de vida.",
    "Para esclerose múltipla, siga as orientações médicas para controle dos sintomas e tratamento.",
    "Em caso de epilepsia, siga rigorosamente o tratamento com medicamentos anticonvulsivantes prescrito pelo médico.",
    "Se houver glaucoma, siga rigorosamente o tratamento oftalmológico para evitar a perda da visão.",
    "Para catarata, consulte um oftalmologista para avaliação e possível cirurgia.",
    "Em caso de degeneração macular, siga as orientações do oftalmologista para controle da progressão da doença.",
    "Se houver rinite alérgica, evite o contato com alérgenos e use medicamentos anti-histamínicos ou corticoides nasais conforme orientação médica.",
    "Para sinusite, procure um médico para tratamento com medicamentos e/ou outras medidas.",
    "Em caso de otite média, procure um médico para tratamento adequado.",
    "Se houver amigdalite, procure um médico para tratamento com antibióticos se necessário.",
    "Para faringite, procure um médico para tratamento adequado.",
    "Em caso de gastrite, siga a dieta recomendada pelo médico e use medicamentos se prescritos.",
    "Se houver úlcera péptica, siga o tratamento médico com medicamentos e dieta.",
    "Para refluxo gastroesofágico, evite alimentos que desencadeiam os sintomas e use medicamentos se prescritos.",
    "Em caso de síndrome do intestino irritável, siga a dieta e as orientações médicas para controle dos sintomas.",
    "Se houver doença de Crohn, siga o tratamento médico para controle da inflamação.",
    "Para colite ulcerativa, siga o tratamento médico para controle da inflamação.",
    "Em caso de pedra nos rins, procure atendimento médico para controle da dor e tratamento.",
    "Se houver infecção renal, procure atendimento médico para tratamento com antibióticos.",
    "Para insuficiência renal, siga rigorosamente o tratamento médico, incluindo dieta e possível diálise ou transplante.",
    "Em caso de asma, siga o plano de tratamento médico e tenha sempre a bombinha de resgate por perto.",
    "Se houver bronquiolite, procure um médico, especialmente em bebês e crianças pequenas.",
    "Para enfisema pulmonar, siga as orientações médicas para controle dos sintomas e melhora da respiração.",
    "Em caso de fibrose cística, siga rigorosamente o tratamento multidisciplinar.",
    "Se houver trombose venosa profunda, procure atendimento médico imediato para tratamento com anticoagulantes.",
    "Para embolia pulmonar, procure atendimento médico de emergência.",
    "Em caso de infarto agudo do miocárdio, procure atendimento médico de emergência.",
    "Se houver angina, procure atendimento médico para avaliação e tratamento.",
    "Para arritmia cardíaca, siga as orientações do cardiologista para controle do ritmo cardíaco.",
    "Em caso de insuficiência cardíaca, siga rigorosamente o tratamento médico, incluindo medicamentos e dieta.",
    "Se houver acidente vascular cerebral (AVC), procure atendimento médico de emergência.",
    "Para acidente isquêmico transitório (AIT), procure atendimento médico para avaliação e prevenção de AVC.",
    "Em caso de aneurisma cerebral, procure atendimento médico para avaliação e possível tratamento.",
    "Se houver meningite, procure atendimento médico urgente.",
    "Para encefalite, procure atendimento médico urgente.",
    "Em caso de esclerose lateral amiotrófica (ELA), siga as orientações médicas para suporte e cuidados.",
    "Se houver miastenia gravis, siga o tratamento médico para controle da fraqueza muscular.",
    "Para síndrome de Guillain-Barré, procure atendimento médico para tratamento e suporte.",
    "Em caso de neuropatia periférica, procure um médico para identificar a causa e seguir o tratamento adequado.",
    "Se houver herpes zoster, procure um médico para tratamento com antivirais e controle da dor.",
    "Para celulite (infecção de pele), procure um médico para tratamento com antibióticos.",
    "Em caso de erisipela, procure um médico para tratamento com antibióticos.",
    "Se houver impetigo, procure um médico para tratamento com antibióticos tópicos ou orais.",
    "Para furúnculo, aplique compressas mornas e procure um médico se não melhorar ou se houver sinais de infecção mais grave.",
    "Em caso de carbúnculo, procure um médico para tratamento, que pode incluir antibióticos e drenagem.",
    "Se houver micose de pele, use antifúngicos tópicos conforme orientação médica.",
    "Para candidíase, use antifúngicos tópicos ou orais conforme orientação médica.",
    "Em caso de dermatite de contato, evite o contato com a substância irritante e use cremes com corticoides se necessário.",
    "Se houver eczema (dermatite atópica), siga as orientações do dermatologista para controle da inflamação e coceira.",
    "Para psoríase, siga as orientações do dermatologista para tratamento das lesões de pele.",
    "Em caso de acne, siga as orientações do dermatologista para tratamento com produtos tópicos e/ou orais.",
    "Se houver rosácea, siga as orientações do dermatologista para controle dos sintomas.",
    "Para urticária, use anti-histamínicos e procure um médico se os sintomas persistirem ou forem graves.",
    "Em caso de lupus eritematoso sistêmico, siga rigorosamente o tratamento médico com imunossupressores e outros medicamentos.",
    "Se houver artrite reumatoide, siga rigorosamente o tratamento médico com medicamentos para controle da inflamação e da dor.",
    "Para espondilite anquilosante, siga as orientações médicas para controle da dor e da rigidez.",
    "Em caso de fibromialgia, siga as orientações médicas para controle da dor e outros sintomas.",
    "Se houver síndrome de Sjögren, siga as orientações médicas para controle dos sintomas de secura.",
    "Para gota, siga as orientações médicas para controle da dor e prevenção de crises.",
    "Em caso de osteoporose, siga as orientações médicas para prevenção de fraturas, incluindo suplementação de cálcio e vitamina D e medicamentos se necessário.",
    "Se houver escoliose, siga as orientações médicas, que podem incluir fisioterapia ou uso de colete.",
    "Para lordose, siga as orientações médicas, que podem incluir fisioterapia e exercícios de fortalecimento.",
    "Em caso de cifose, siga as orientações médicas, que podem incluir fisioterapia e exercícios posturais.",
    "Se houver hérnia de disco, siga as orientações médicas, que podem incluir repouso, fisioterapia e, em alguns casos, cirurgia.",
    "Para estenose espinhal, siga as orientações médicas para controle da dor e outros sintomas.",
    "Em caso de bursite, repouse a área afetada e procure orientação médica.",
    "Se houver tendinite, repouse a área afetada e aplique gelo.",
    "Para fascite plantar, siga as orientações médicas, que podem incluir repouso, alongamento e uso de palmilhas.",
    "Em caso de síndrome do túnel do carpo, siga as orientações médicas, que podem incluir repouso, uso de órtese e, em alguns casos, cirurgia.",
    "Se houver epicondilite, repouse o braço e procure orientação médica.",
    "Para epitrocleíte, repouse o braço e procure orientação médica.",
    "Em caso de torcicolo, aplique calor e faça movimentos suaves.",
    "Se houver contusão, aplique gelo na área afetada.",
    "Para distensão muscular, repouse a área afetada e aplique gelo.",
    "Em caso de rompimento de ligamento, procure atendimento médico para avaliação e tratamento.",
    "Se houver luxação, procure atendimento médico para que a articulação seja recolocada no lugar.",
    "Para fratura exposta, cubra o ferimento com um pano limpo sem pressionar e procure atendimento médico de emergência.",
    "Em caso de traumatismo cranioencefálico, procure atendimento médico de emergência.",
    "Se houver queimadura solar, aplique hidratante e evite a exposição ao sol.",
    "Para picada de aranha, lave o local com água e sabão e procure atendimento médico se houver sintomas como dor intensa ou dificuldade para respirar.",
    "Em caso de picada de cobra, mantenha a pessoa calma e imóvel, lave o local com água e sabão e procure atendimento médico de emergência levando a cobra (se seguro) ou fotos dela para identificação do veneno.",
    "Se houver choque elétrico, desligue a fonte de energia antes de tocar na vítima e procure atendimento médico.",
    "Para afogamento, inicie a ressuscitação cardiopulmonar (RCP) imediatamente e procure atendimento médico.",
    "Em caso de queda, avalie a pessoa e procure atendimento médico se houver dor intensa ou incapacidade de movimentar a área afetada.",
    "Se houver acidente de trânsito, verifique se há feridos e chame os serviços de emergência.",
    "Para queimaduras químicas, lave a área afetada com água corrente por pelo menos 20 minutos e procure atendimento médico.",
    "Em caso de intoxicação, ligue para o centro de controle de intoxicações e siga as orientações.",
    "Se houver ingestão de substâncias tóxicas, não induza o vômito a menos que indicado por um profissional de saúde.",
    "Para reações adversas a medicamentos, procure atendimento médico imediatamente.",
    "Em caso de overdose, procure atendimento médico de emergência.",
    "Se houver sinais de desidratação, como boca seca e urina escura, ofereça líquidos e procure ajuda médica se não houver melhora.",
    "Para insolação, leve a pessoa para um local fresco e ofereça líquidos.",
    "Em caso de hipotermia, leve a pessoa para um local aquecido e cubra-a com cobertores.",
    "Se houver hemorragia, aplique pressão direta sobre o local e procure atendimento médico.",
    "Em caso de dor de dente, enxágue a boca com água morna, use fio dental para remover resíduos e evite aplicar calor diretamente na área. Procure um dentista o quanto antes.",
    "Para alívio de hemorroidas, mantenha a região limpa, faça banhos de assento com água morna e evite esforço ao evacuar. Consulte um médico se houver sangramento, dor intensa ou persistência dos sintomas.",
    "Em caso de febre alta, mantenha-se hidratado, use roupas leves e, se necessário, use medicamentos antitérmicos conforme orientação médica. Procure atendimento se a febre persistir por mais de 48 horas ou vier acompanhada de outros sintomas graves.",
    "Durante uma crise de asma, use o broncodilatador prescrito, sente-se em posição confortável e mantenha a calma. Procure atendimento médico se não houver melhora rápida.",
    "Para cortes profundos, lave com água corrente, aplique pressão com um pano limpo para estancar o sangramento e procure atendimento médico para avaliação e possível sutura.",
    "Em caso de entorse, aplique gelo por 20 minutos, eleve o membro afetado e evite apoiar peso. Procure avaliação médica para descartar fraturas.",
    "Em caso de dor no joelho, evite esforço, aplique gelo por 20 minutos e mantenha a perna elevada. Se a dor persistir, estiver associada a inchaço ou dificuldade para se mover, procure avaliação médica.",
    "Em caso de dor nas pernas, evite esforço físico, aplique compressas frias ou mornas conforme o alívio percebido e mantenha as pernas elevadas. Se a dor for intensa, persistente ou acompanhada de inchaço, procure avaliação médica.",
    "Em caso de dor nas costas, aplique compressas mornas, evite esforço físico e mantenha uma boa postura. Se a dor persistir ou for intensa, procure avaliação médica.",
    "Em caso de dor no peito, procure atendimento médico imediatamente, especialmente se acompanhada de falta de ar, sudorese ou dor irradiada para o braço esquerdo.",
    "Em caso de dor abdominal intensa, evite comer ou beber até ser avaliado por um médico. Procure atendimento médico imediatamente.",
    "Se houver dor ao urinar, beba bastante água e procure um médico para avaliação.",
    "Para dor de garganta, faça gargarejos com água morna e sal e procure um médico se a dor persistir ou houver dificuldade para engolir.",
    "Em caso de dor de ouvido, aplique compressas mornas e procure um médico se a dor persistir ou houver secreção.",
    "Se houver dor de cabeça intensa, desmaio ou confusão mental, procure atendimento médico imediatamente.",
    "Para dor de estômago, evite alimentos sólidos e procure um médico se a dor persistir ou houver vômito.",
    "Em caso de dor nas articulações, evite esforço físico e aplique gelo na área afetada. Se a dor persistir ou houver inchaço, procure avaliação médica.",
    "Se houver dor no peito, procure atendimento médico imediatamente.",
    "Para dor abdominal intensa, evite comer ou beber até ser avaliado por um médico. Procure atendimento médico imediatamente.",
    "Em caso de dor nas costas, aplique compressas mornas e evite esforço físico. Se a dor persistir ou for intensa, procure avaliação médica.",
    "Se houver dor no joelho, evite esforço, aplique gelo por 20 minutos e mantenha a perna elevada. Se a dor persistir, estiver associada a inchaço ou dificuldade para se mover, procure avaliação médica.",
    "Para dor nas pernas, evite esforço físico, aplique compressas frias ou mornas conforme o alívio percebido e mantenha as pernas elevadas. Se a dor for intensa, persistente ou acompanhada de inchaço, procure avaliação médica.",
    "Em caso de dor no peito, procure atendimento médico imediatamente, especialmente se acompanhada de falta de ar, sudorese ou dor irradiada para o braço esquerdo.",
    "Se houver dor ao urinar, beba bastante água e procure um médico para avaliação.",
    "cardiologista:Hipertensão, Infarto, Arritmia, Insuficiência cardíaca",
    "pediatra:Infecções, Doenças respiratórias, Alergias, Doenças crônicas",
    "dermatologista:Acne, Eczema, Psoríase, Câncer de pele",
    "ginecologista:Menstruação, Gravidez, Menopausa, Infecções vaginais",
    "urologista:Infecções urinárias, Cálculos renais, Problemas de próstata, Disfunção erétil",
    "ortopedista:Fraturas, Entorses, Lesões esportivas, Problemas articulares",
    "neurologista:Dores de cabeça, Epilepsia, Doença de Parkinson, Esclerose múltipla",
    "endocrinologista:Diabetes, Hipotireoidismo, Hipertireoidismo, Obesidade",
    "psiquiatra:Depressão, Ansiedade, Transtornos alimentares, Esquizofrenia",
    "psicólogo:Depressão, Ansiedade, Estresse, Relacionamentos",
    "fisioterapeuta:Reabilitação, Exercícios terapêuticos, Tratamento de dor, Prevenção de lesões",
    "nutricionista:Dieta equilibrada, Controle de peso, Doenças metabólicas, Alergias alimentares",
    "oftalmologista:Problemas de visão, Catarata, Glaucoma, Doenças da retina",
    "otorrinolaringologista:Problemas auditivos, Sinusite, Amigdalite, Zumbido",
    "cardiologista:Hipertensão, Infarto, Arritmia, Insuficiência cardíaca",
    "pneumologista:Asma, DPOC, Pneumonia, Apneia do sono",
    "gastroenterologista:Doenças do fígado, Doenças intestinais, Refluxo gastroesofágico, Úlceras",
    "reumatologista:Artrite, Lupus, Fibromialgia, Osteoporose",
    "hematologista:Anemia, Leucemia, Linfoma, Hemofilia",
    "oncologista:Câncer, Quimioterapia, Radioterapia, Cuidados paliativos",
    "infectologista:Infecções, Doenças infecciosas, Imunizações, Tratamento de doenças infecciosas",
    "pediatra:Infecções, Doenças respiratórias, Alergias, Doenças crônicas",
    "geriatria:Doenças crônicas, Cuidados paliativos, Saúde mental, Mobilidade",
    "endocrinologista:Diabetes, Hipotireoidismo, Hipertireoidismo, Obesidade",
    "nutrição:Dieta equilibrada, Controle de peso, Doenças metabólicas, Alergias alimentares",
    "fisioterapia:Reabilitação, Exercícios terapêuticos, Tratamento de dor, Prevenção de lesões",
    "psicologia:Depressão, Ansiedade, Estresse, Relacionamentos",
    "psiquiatria:Depressão, Ansiedade, Transtornos alimentares, Esquizofrenia",
    "ortopedia:Fraturas, Entorses, Lesões esportivas, Problemas articulares",
    "neurologia:Dores de cabeça, Epilepsia, Doença de Parkinson, Esclerose múltipla",
    "pneumologia:Asma, DPOC, Pneumonia, Apneia do sono",
    "gastroenterologia:Doenças do fígado, Doenças intestinais, Refluxo gastroesofágico, Úlceras",
    "reumatologia:Artrite, Lupus, Fibromialgia, Osteoporose",
    "hematologia:Anemia, Leucemia, Linfoma, Hemofilia",
    "oncologia:Câncer, Quimioterapia, Radioterapia, Cuidados paliativos",
    "infectologia:Infecções, Doenças infecciosas, Imunizações, Tratamento de doenças infecciosas",
    "geriatria:Doenças crônicas, Cuidados paliativos, Saúde mental, Mobilidade",
    "endocrinologia:Diabetes, Hipotireoidismo, Hipertireoidismo, Obesidade",
    "nutrição:Dieta equilibrada, Controle de peso, Doenças metabólicas, Alergias alimentares",
    "fisioterapia:Reabilitação, Exercícios terapêuticos, Tratamento de dor, Prevenção de lesões",
    "psicologia:Depressão, Ansiedade, Estresse, Relacionamentos",
    "psiquiatria:Depressão, Ansiedade, Transtornos alimentares, Esquizofrenia",
    "ortopedia:Fraturas, Entorses, Lesões esportivas, Problemas articulares",
    "neurologia:Dores de cabeça, Epilepsia, Doença de Parkinson, Esclerose múltipla",
    "Em caso de picada de abelha, remova o ferrão com cuidado, lave a área com água e sabão e aplique uma compressa fria.",
    "Se picado por uma vespa, lave o local com água e sabão e aplique gelo para reduzir o inchaço."
    "Em caso de picada de formiga venenosa, lave a área com água e sabão e procure atendimento médico se houver reação intensa."
    "Se houver picada de aranha, lave o local com água e sabão, mantenha a área elevada e procure atendimento médico."
    "Em caso de picada de escorpião, lave o local com água e sabão e procure atendimento médico imediatamente.",
    "Se for picado por uma lacraia, lave a área com água e sabão e aplique compressa fria para aliviar a dor.",
    "Em caso de picada de carrapato, remova o inseto cuidadosamente, lave a área com água e sabão e observe sinais de infecção."
    "Após picada de mosquito, lave o local com água e sabão e evite coçar para prevenir infecção.",
    "Em caso de picada de marimbondo, lave o local com água e sabão e aplique compressa fria para reduzir a dor e o inchaço.",
    "Se houver picada de taturana, lave a área com água fria corrente sem esfregar e procure atendimento médico.",
    "Em caso de mordida de animal peçonhento, como cobra, mantenha a vítima calma, imobilize o local e busque atendimento médico imediatamente.",
    "Se for picado por peixe venenoso, como bagre ou arraia, lave o ferimento e mergulhe o local em água quente enquanto aguarda ajuda médica.",
    "Em caso de picada de abelha, remova o ferrão com cuidado, lave a área com água e sabão e aplique uma compressa fria.",
    "Em caso de picada de cobra, mantenha a vítima calma, imobilize o membro afetado e procure atendimento médico urgente."
    "Em caso de dor de barriga leve, repouse e mantenha-se hidratado,",
    "Se a dor de barriga for acompanhada de febre, vômito ou sangue nas fezes, procure atendimento médico,",
    "Evite alimentos gordurosos ou muito condimentados em caso de dor de barriga,",
    "Mantenha uma alimentação leve, com líquidos e alimentos de fácil digestão, durante episódios de dor de barriga,",
    "Se a dor de barriga persistir por mais de 24 horas, procure orientação médica,",
    "Para dor de barriga causada por gases, caminhe levemente e evite bebidas gaseificadas,",
    "Em casos de diarreia intensa, reponha líquidos com soluções de reidratação oral,",
    "Se houver sinais de desidratação junto com dor de barriga, como boca seca e tontura, procure ajuda médica imediatamente,",
    "Evite automedicação em casos de dor abdominal intensa ou persistente,",
    "Em caso de dor de barriga súbita e muito forte, procure atendimento médico de emergência,"
]
